[package]
name       = "tracy-gizmos"
version    = "0.1.0"
authors    = ["Denys Mentiei <endden@gmail.com>"]
repository = "https://github.com/den-mentiei/tracy-gizmos"
license    = "MIT OR Apache-2.0"
readme     = "README.md"
keywords   = ["profiler", "performance", "tracy", "api-bindings"]
categories = ["development-tools::profiling", "api-bindings"]
edition    = "2021"

[dependencies]

[workspace]
members = ["sys"]