[package]
name                 = "tracy-gizmos-attributes"
version              = "0.1.0"
authors.workspace    = true
repository.workspace = true
license.workspace    = true
edition.workspace    = true
publish              = false # @Incomplete

[lib]
proc-macro = true

[dependencies]
