[package]
name    = "tracy-gizmos-examples"
publish = false
edition = "2021"

[dev-dependencies]
tracy-gizmos = { path = "../tracy-gizmos" }

[features]
default      = []
instrumented = ["tracy-gizmos/enabled"]
